#!/bin/sh
# Copyright (C) 2016 Jeffery To

set -o errexit

me=$(basename "$0")

if autoreconf --version >/dev/null 2>&1; then
	autoreconf --install --verbose "$@"
else
	echo "$me: running: aclocal $@"
	aclocal "$@"

	echo "$me: running: autoconf $@"
	autoconf "$@"

	echo "$me: running: automake --add-missing --copy $@"
	automake --add-missing --copy "$@"
fi

echo
echo "Ready for \`cd build && ../configure && make && make install'"
